---
title: "Moorea LTER"
author: "Carmen Hoyt"
date: last-modified
format:
  html:
      toc: true
      code-fold: true
editor: visual
execute:
  warning: false
  messages: false
editor_options: 
  chunk_output_type: console
---

# Moorea Coral Reef LTER 

[Data](https://mcr.lternet.edu/data)

## Data

[benthic water temperature](https://portal.edirepository.org/nis/metadataviewer?packageid=knb-lter-mcr.1035.16):
- temp (C)
- sites 1-6

[Population Dynamics of Acanthaster planci (crown of thorns)](https://portal.edirepository.org/nis/metadataviewer?packageid=knb-lter-mcr.1039.11)
- counts
- sites 1-6

## Question:

**Does benthic water temperature correlate with crown of thorns abundance?**

## Load Packages

```{r}
#| code-summary: Load Packages
library(tidyverse)
library(here)
library(janitor)
library(lubridate)
library(DBI)
library(duckdb)
library(patchwork)
library(sessioninfo)
```

## Load Data

```{r}
#| code-summary: Load Data

# -------- Water Temp --------
# Read in filenames for all LTER sites
water_temp_filenames <- list.files("/Users/choyt/MEDS/eds213-databases/eds-213-discussion/moorrea-LTER-data/benthic-water-temp", full.names=TRUE)

# Create an empty list
all_LTER_sites_water <- vector("list", length = length(water_temp_filenames))

# Loop through filenames
for (i in seq_along(water_temp_filenames)) {
  # Read in files
  df <- read_csv(water_temp_filenames[i], show_col_types = FALSE)
  # Name the df
  df_name <- paste0("LTER0", i-1)
  # Append df to empty list
  all_LTER_sites_water[[i]] <- assign(df_name, df)
}

# Create df for all LTER sites
benthic_water_temp <- bind_rows(all_LTER_sites_water) %>%
  clean_names()

# -------- Crown of Thorns Abundance --------
ac_abundance <- read_csv("/Users/choyt/MEDS/eds213-databases/eds-213-discussion/moorrea-LTER-data/MCR_LTER_COTS_abundance_2005-2022_20220503.csv", show_col_types = FALSE) %>%
  clean_names()
```

## Clean Data

```{r}
#| code-summary: Clean Data

# Clean water temp data
benthic_water_temp_cleaned <- benthic_water_temp %>%
  # Extract year from time_local
  mutate(time_local = as_date(time_local)) %>%
  mutate(year = year(time_local)) %>%
  select(-c(time_utc))

sum(is.na(benthic_water_temp_cleaned$temperature_c)) #0
unique(benthic_water_temp_cleaned$year)
unique(benthic_water_temp_cleaned$site)

# Clean ac abundance data
ac_abundance_cleaned <- ac_abundance %>%
  # Convert site to match water temp
  mutate(site = case_when(
    site == "LTER 1" ~ "LTER01",
    site == "LTER 2" ~ "LTER02",
    site == "LTER 3" ~ "LTER03",
    site == "LTER 4" ~ "LTER04",
    site == "LTER 5" ~ "LTER05",
    site == "LTER 6" ~ "LTER06"
  )) %>%
  rename(a_planci_counts = cots)

sum(is.na(ac_abundance_cleaned$a_planci_counts)) #0
unique(ac_abundance_cleaned$year)
unique(ac_abundance_cleaned$site)

# Save cleaned data
write_csv(benthic_water_temp_cleaned, here("clean-data", "benthic_water_temp_cleaned.csv"))
write_csv(ac_abundance_cleaned, here("clean-data", "ac_abundance_cleaned.csv"))
```

## Create Database

See moorea-LTER.sql

## Creat Visualization

```{r}
#| code-summary: Visualize

# Connect to database
conn <- DBI::dbConnect(duckdb::duckdb(), dbdir="moorea-LTER.db")

# Look at tables
DBI::dbListTables(conn)

# Import final table for vis
final_year_df <- dbGetQuery(conn, "SELECT * FROM final_year")


# Visualize abundance over time
p1 <- final_year_df %>%
  group_by(year) %>%
  summarise(avg_temp = mean(avg_temp),
            abund = sum(abundance)) %>%
  ggplot(aes(year, abund)) +
  geom_line(color = "firebrick") +
  labs(x = "",
       y = "Abundance",
       title = "Crown of Thorn Starfish (A. planci) Abundance and Water Temperature over Time (2005-2022)") +
  theme_minimal() +
  theme(axis.ticks.x = element_blank(),
        axis.text.x = element_blank())

# Visualize avg temp over time
p2 <- final_year_df %>%
  group_by(year) %>%
  summarise(avg_temp = mean(avg_temp),
            abund = sum(abundance)) %>%
  ggplot(aes(year, avg_temp)) +
  geom_line(color = "cornflowerblue") +
  labs(x = "Year",
       y = "Average Temperature (°C)") +
  theme_minimal()

# Combine graphs
p1/p2

# Abundance vs temperature
ggplot(final_year_df, aes(avg_temp, abundance)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, color = "purple") +
  labs(x = "Average Temperature (°C)",
       y = "Abundance",
       title = "Crown of Thron Starfish (A. planci) Abundance vs. Water Temperature") +
  theme_minimal()

# Disconnect
DBI::dbDisconnect(conn, shutdown = TRUE)
```

